### PR TITLE
Handle ntree_limit higher than number of trees in GBTree and Dart model in graceful way

### PR DESCRIPTION
**Pull request by jbojar**
If ntree_limit is set too high it uses maximum available trees in GBTree and Dart predictors.

It resolves issue #34.

### CODE REVIEW

**Comment by jbojar** [comment]
I had to bump jdk version to 8 because of strange issues with travis and unsupported jdk7.

**Comment by kretes** [comment]
@komiya-atsushi is there a chance to merge that and get an official version?

**Comment by komiya-atsushi** [comment]
Thanks!

**Comment by komiya-atsushi** [comment]
@kretes I have just released [xgboost-predictor 0.3.1](https://bintray.com/komiya-atsushi/maven/xgboost-predictor/0.3.1)

**Pull request merged**
